import jsPDF from 'jspdf'

class PDFService {
  /**
   * Generate PDF from letter content with Malaysian formatting
   * @param {string} letterContent - The letter text content
   * @param {object} metadata - Letter metadata (letter_type, language, etc.)
   * @returns {jsPDF} PDF document
   */
  generateLetterPDF(letterContent, metadata = {}) {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 25 // Malaysian standard margin
    const maxWidth = pageWidth - (margin * 2)

    // Set font
    doc.setFont('helvetica')
    doc.setTextColor(0, 0, 0)

    const lines = letterContent.split('\n')
    let y = margin
    const lineSpacing = 6 // Standard line spacing

    lines.forEach((line, index) => {
      // Check if we need a new page
      if (y > pageHeight - margin - 20) {
        doc.addPage()
        y = margin
      }

      const trimmedLine = line.trim()

      // Empty line - add spacing
      if (trimmedLine === '') {
        y += lineSpacing / 2
        return
      }

      // Subject line (Re: or Rujukan:)
      if (trimmedLine.startsWith('Re:') || trimmedLine.startsWith('Rujukan:')) {
        doc.setFontSize(11)
        doc.setFont('helvetica', 'bold')
        const wrappedText = doc.splitTextToSize(trimmedLine, maxWidth)
        doc.text(wrappedText, margin, y)
        y += wrappedText.length * lineSpacing + 3
        doc.setFont('helvetica', 'normal')
        return
      }

      // Salutation (Dear Sir/Madam, Tuan/Puan, etc.)
      if (trimmedLine.match(/^(Dear|Tuan|Puan|Yang Berhormat|YB)/i)) {
        doc.setFontSize(11)
        doc.setFont('helvetica', 'normal')
        doc.text(trimmedLine, margin, y)
        y += lineSpacing + 2
        return
      }

      // Closing (Yours faithfully, Yang benar, etc.)
      if (trimmedLine.match(/^(Yours faithfully|Yours sincerely|Yang benar|Sekian)/i)) {
        doc.setFontSize(11)
        doc.setFont('helvetica', 'normal')
        doc.text(trimmedLine, margin, y)
        y += lineSpacing + 2
        return
      }

      // Date formatting (detect dates)
      if (trimmedLine.match(/^\d{1,2}\s+(January|February|March|April|May|June|July|August|September|October|November|December|Januari|Februari|Mac|April|Mei|Jun|Julai|Ogos|September|Oktober|November|Disember)\s+\d{4}$/i)) {
        doc.setFontSize(11)
        doc.setFont('helvetica', 'normal')
        doc.text(trimmedLine, margin, y)
        y += lineSpacing + 3
        return
      }

      // Short lines (likely addresses, names, titles) - smaller spacing
      if (trimmedLine.length < 60 && !trimmedLine.endsWith('.')) {
        doc.setFontSize(11)
        doc.setFont('helvetica', 'normal')
        const wrappedText = doc.splitTextToSize(trimmedLine, maxWidth)
        doc.text(wrappedText, margin, y)
        y += wrappedText.length * lineSpacing
        return
      }

      // Regular paragraphs
      doc.setFontSize(11)
      doc.setFont('helvetica', 'normal')
      const wrappedText = doc.splitTextToSize(trimmedLine, maxWidth)
      doc.text(wrappedText, margin, y)
      y += wrappedText.length * lineSpacing + 2
    })

    // Footer
    this.addFooter(doc, metadata)

    return doc
  }

  /**
   * Add footer to PDF with metadata
   */
  addFooter(doc, metadata) {
    const pageHeight = doc.internal.pageSize.getHeight()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 25

    const footerY = pageHeight - 15
    doc.setFontSize(8)
    doc.setTextColor(120, 120, 120)

    const letterType = this.formatLetterType(metadata?.letter_type)
    const language = this.formatLanguage(metadata?.language)
    const date = new Date().toLocaleDateString('en-MY', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })

    const footerText = `Generated by Catat • ${letterType} • ${language} • ${date}`
    
    // Center the footer
    const textWidth = doc.getTextWidth(footerText)
    const centerX = (pageWidth - textWidth) / 2
    
    doc.text(footerText, centerX, footerY)
  }

  /**
   * Format letter type for display
   */
  formatLetterType(type) {
    const types = {
      complaint: 'Complaint Letter',
      proposal: 'Proposal',
      mc: 'MC Letter',
      general: 'General Letter',
      official: 'Official Letter'
    }
    return types[type] || 'Letter'
  }

  /**
   * Format language for display
   */
  formatLanguage(lang) {
    const languages = {
      en: 'English',
      ms: 'Bahasa Malaysia',
      mixed: 'Mixed'
    }
    return languages[lang] || 'English'
  }

  /**
   * Download PDF to user's device
   */
  downloadPDF(doc, filename = 'letter.pdf') {
    doc.save(filename)
  }

  /**
   * Open PDF in new browser tab
   */
  openPDFInNewTab(doc) {
    const pdfBlob = doc.output('blob')
    const url = URL.createObjectURL(pdfBlob)
    window.open(url, '_blank')
  }

  /**
   * Get PDF as blob (for uploading to storage)
   */
  getPDFBlob(doc) {
    return doc.output('blob')
  }

  /**
   * Get PDF as base64 string
   */
  getPDFBase64(doc) {
    return doc.output('datauristring')
  }
}

export const pdfService = new PDFService()
